### ISSUE TITLE
buggy usage on symptom drop down menu

### ISSUE THREAD

**Issue by hueseyinkilic** [p3t3r67x0/illness-webapp#11]
- It would be optimal if you could select several symptoms at once 
- after each click the selection field disappears
and the bar below the actual symptom bar always folds out.
![image](https://user-images.githubusercontent.com/56175686/77261698-93dc4c00-6c90-11ea-9b6b-afac4ac5b390.png)

**Comment by hueseyinkilic** [comment]
multi select fixed

**Comment by hueseyinkilic** [comment]
in master

**Comment by 40818419** [comment]
top
