### ISSUE TITLE
results page entries seem to be looping?

### ISSUE THREAD

**Issue by hueseyinkilic** [p3t3r67x0/illness-webapp#12]
- i have made 1 entry for PLZ 12346, but as you see, when I search, there are so many results as seen on the scroll bar

- it seems like there is something wrong :D
![image](https://user-images.githubusercontent.com/56175686/77262137-0e5a9b00-6c94-11ea-9894-affa39aa6a3f.png)

**Comment by 40818419** [comment]
fixed in https://github.com/p3t3r67x0/illness-webapp/commit/713d371e416354c72f8fac422482e1fcffd7ff11
